swagger: "2.0"
info:
  title: "LAN Users API"
  version: "1.0.0"
paths:
  /users:
    get:
      produces:
        - string
      responses:
        "200":
          description: "Success"
          schema:
            type: string
      operationId: "usersa"
      tags:
        - "lanUsers"

definitions:
  test:
    type: "object"
    properties:
      aa:
        type: "string"
